# Generated by Django 3.0.7 on 2020-07-08 21:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('table', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='encounter',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
