# Generated by Django 3.0.7 on 2020-07-08 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('table', '0002_encounter_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='encounter',
            name='time',
            field=models.TimeField(default='00:00'),
        ),
    ]
