# Generated by Django 3.0.7 on 2020-07-09 18:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('table', '0003_encounter_time'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='encounter',
            unique_together={('sha256', 'date', 'time')},
        ),
        migrations.CreateModel(
            name='Scores',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.PositiveSmallIntegerField(blank=True, default=None, null=True)),
                ('encounter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='encounter', to='table.Encounter')),
            ],
        ),
    ]
