# Generated by Django 3.0.7 on 2020-07-09 19:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('table', '0007_score_score_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='score',
            name='encounter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scores', to='table.Encounter'),
        ),
    ]
