# Generated by Django 3.0.7 on 2020-07-14 21:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('table', '0008_auto_20200709_1511'),
    ]

    operations = [
        migrations.AlterField(
            model_name='score',
            name='encounter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='encounter_scores', to='table.Encounter'),
        ),
    ]
