# Generated by Django 3.0.7 on 2020-07-24 15:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('table', '0011_auto_20200714_1728'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='encounter',
            unique_together=set(),
        ),
    ]
