# Generated by Django 3.0.7 on 2021-01-18 02:29

from django.db import migrations, models
import table.models


class Migration(migrations.Migration):

    dependencies = [
        ('table', '0013_encounter_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='encounter',
            name='image',
            field=models.ImageField(blank=True, default=None, upload_to=table.models.directory_path),
        ),
    ]
