version: '3.7'

services:

  frontend:
    container_name: frontent
    build:
      context: ./phishingnet
      dockerfile: Dockerfile
    volumes:
      - '/app'
      - '/app/node_modules'
    ports:
      - "3000:3000"
    environment:
      - CHOKIDAR_USEPOLLING=true
    stdin_open: true
    tty: true

  db:
    image: postgres
    environment:
      - POSTGRES_DB=mydb
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=lorencia
    ports:
      - "5432:5432"
    volumes:
      - postgres-db:/var/lib/postgresql/data
  web:
    container_name: backend
    build:
      context: ./djangophish
      dockerfile: Dockerfile
    command: > 
            bash -c "
            python manage.py makemigrations;
            python manage.py migrate;
            python manage.py initadmin;
            python manage.py runserver 0.0.0.0:8000;"
    volumes:
      - frontend-db:/local
    ports:
      - "8000:8000"
    depends_on:
      - db
volumes:
  postgres-db:
  frontend-db:
