  version: '3'
    
  services:
    db:
      image: postgres
      environment:
        - POSTGRES_DB=mydb
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=lorencia
      ports:
        - "5432:5432"
      volumes:
        - postgres-db:/var/lib/postgresql/data
    web:
      build: .
      command: > 
            bash -c "
            python manage.py makemigrations;
            python manage.py migrate;
            python manage.py initadmin;
            python manage.py runserver 0.0.0.0:8000;"
      volumes:
        - frontend:/local
      ports:
        - "8000:8000"
      depends_on:
        - db
  volumes:
    postgres-db:
    frontend: